### PR TITLE
0.31.0

### PR DESCRIPTION
**Pull request by littledivy**
#244 added `console_error_panic_hook` added a wasm dependency without respecting the feature.

### CODE REVIEW

**Review by kitsonk — CHANGES_REQUESTED** [review]
We need to rebuild the WASM libraries as part of these PRs.  It is not integrated into CI yet.

**Comment by littledivy** [comment]
Rebuilt.

**Review by kitsonk — CHANGES_REQUESTED** [review]
Usually when you do a version bump, it affects the generated JS.  I noticed it wasn't part of the PR, so I checked out the PR and ran the build script:

```
@kitsonk ➜ /workspaces/deno_doc (pr/littledivy/245) $ ./_build.ts
Building deno_doc web assembly...
  cargo fmt
  cargo build --release --no-default-features --features wasm --target wasm32-unknown-unknown
   Compiling deno_doc v0.31.0 (/workspaces/deno_doc)
    Finished release [optimized] target(s) in 15.63s
  wasm-bindgen ./target/wasm32-unknown-unknown/release/deno_doc.wasm --target deno --weak-refs --out-dir ./target/wasm32-bindgen-deno-js
Copying lib wasm...
  copy ./lib/deno_doc_bg.wasm
Generating lib JS bindings...
  write ./lib/deno_doc.generated.js
  deno fmt --quiet ./lib/deno_doc.generated.js
Finished deno_doc web assembly.
@kitsonk ➜ /workspaces/deno_doc (pr/littledivy/245 ✗) $ git status
On branch pr/littledivy/245
Your branch is up to date with 'littledivy/0.31.0'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   lib/deno_doc.generated.js
        modified:   lib/deno_doc_bg.wasm

no changes added to commit (use "git add" and/or "git commit -a")
```

Can we please ensure the PR is update to date and accurate with the build script.

I have also noticed the the build script isn't idempotent with main right now either.  That isn't good.

**Comment by littledivy** [comment]
Everything is up to date. I've tried deleting the JS but it still shows no diff. My wasm-bindgen-cli version is 0.2.79

**Review by kitsonk — APPROVED** [review]
Ok, not sure what is going on that the builds aren't reproducible, they should be, but there doesn't seem to be a problem with it.

**Pull request merged**
