### PR TITLE
Release 0.14.0

### PR DESCRIPTION
**Pull request by kitsonk**
We should try to get another version into Deno 1.14 as there are some handy new features.

### CODE REVIEW

**Review by bartlomieju — APPROVED** [review]
LGTM

**Comment by dsherret** [comment]
We should do another release of deno_ast first before bothering with this. There was a fix in there to make static blocks work in JS code (was missing on the ESConfig property).

I've opened https://github.com/denoland/deno_ast/pull/9

**Comment by kitsonk** [comment]
I will update the pr in a minute

**Comment by dsherret** [comment]
@kitsonk I tried to and I'm getting:

```
wasm-bindgen ./target/wasm32-unknown-unknown/release/deno_doc.wasm --target deno --weak-refs --out-dir ./target/wasm32-bindgen-deno-js
thread 'main' panicked at 'remaining data [19]', /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.76/src/descriptor.rs:110:9
```

I'll push what I have so far.

**Comment by kitsonk** [comment]
@dsherret you need to update the version of wasm_bindgen_cli you have installed locally to match the version in the Cargo.toml.

**Comment by dsherret** [comment]
@kitsonk interesting... thanks!

**Review by dsherret — APPROVED** [review]

**Pull request merged**
