### PR TITLE
feat: structure JSDoc better

### PR DESCRIPTION
**Pull request by kitsonk**
Closes: #141

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
Looks good overall.

I do wonder if we could not use the `jsdoc` crate for parsing? It is maintained by Kang. He is likely using it for STC, so I have relatively high confidence in it. Feels a lot more robust than regex matching.

**Comment by kitsonk** [comment]
Ooops... ok, I will take a look at that. You question my Regex authoring? 😉

**Comment by lucacasonato** [comment]
I would never dare question your regexp authoring 😅

**Comment by kitsonk** [comment]
@lucacasonato I looked into the `jsdoc` crate... I think there are a few issues that mean integrating it right now would be problematic:

- For some reason any leading docs don't get stripped of their ` * `.  So this:

   ```js
    /**
     * Some leading comment
     * across multiple lines
     * 
     * @param {string} b comment
    ```

    Gets parsed out as `Some leading comment\n * across multiple lines\n *\n * `.  That could be intentional or unintentional, it is really hard to tell.
- Processing of the tags to put into structures is rather complicated, and it seems the tags only include what is meaningful for inferring types, versus generating documentation, like a lot of the tags can have comments/doc associated with them, but are just not part of the parse.  Getting stuff back out of the JSDoc "AST" into structures useful for documentation is complicated.
- The crate is changing a lot, I think it is far from a stable API at the moment, and upstreaming changes might is hard due to the lack of any sort of documentation in the code.

So, while it might make sense in the future to integrate `jsdoc`, it feels like it needs to be a bit more settled and a bit more mature.  Integrating it and switching over would be trivial in the future I suspect, but my opinion is that it isn't something we should do right now, and focus on stabilising the output which would make it even easier to modify how it is "parsed" in the future.

**Review by lucacasonato — APPROVED** [review]
Let's do this then 👍

**Comment by irustm** [comment]
Guys, it would be cool to mention this PR in Breacking Changes in the release notes

**Pull request merged**
