### PR TITLE
fix: only include declarations in docs if the file is ambient

### LINKED ISSUE #57: Renamed export retains old name
### Example:
```typescript
declare function foo(): void;
export { foo as bar };
```
#### Expected:
`function bar(): void`
#### Actual:
`function foo(): void`

This is only the case with declarations. If `foo()` was actually implemented here, the output would be correct.

### PR DESCRIPTION
**Pull request by Liamolucko**
Previously, the `declare` keyword was taken to indicate a global variable and shown in the documentation. However, that is only be the case for ambient declarations - in modules, this just indicates a private value.

Partially fixes #57

### CODE REVIEW

**Comment by Liamolucko** [comment]
This actually includes all the changes from #59, which I guess it probably shouldn't, but the goal was to fix #57 and those changes are needed to fix it. Maybe I should undo that?

**Comment by Liamolucko** [comment]
I think I'll leave it to avoid merge conflicts.

**Comment by bartlomieju** [comment]
@Liamolucko please rebase

**Review by bartlomieju — APPROVED** [review]
Cool, thanks @Liamolucko

**Pull request merged**
