### PR TITLE
fix: add `.ddoc` prefix to tailwind classes output

### PR DESCRIPTION
**Pull request by crowlKats**
`ddoc` for a shorter `deno-doc` to not overly bloat up the tailwind output

### CODE REVIEW

**Comment by lucacasonato** [comment]
Even just `dd`?

**Comment by crowlKats** [comment]
that might work, but `dd` is a html element, so maybe just to be clear enough that its something not related to that

**Comment by lucacasonato** [comment]
`.d`? :D

**Comment by crowlKats** [comment]
🤣 a bit too abstract imo. but dont have a strong opinion with any of these, just as long as they are understandable

**Comment by lucacasonato** [comment]
Let's land as is then.

**Review by lucacasonato — APPROVED** [review]

**Pull request merged**
